Write a Python program to create a simple attention score calculation. Use NumPy to generate random values for query, key, and value vectors, then compute the dot product.


In [1]:
import numpy as np

def calculate_attention():
    np.random.seed(42)  # For reproducibility
    
    # Generate random query, key, and value vectors
    query = np.random.rand(1, 4)  # 1x4 vector
    key = np.random.rand(4, 4)    # 4x4 matrix
    value = np.random.rand(4, 4)  # 4x4 matrix
    
    # Compute dot product of query and key (transposed)
    attention_scores = np.dot(query, key.T)
    
    # Apply softmax to normalize scores
    attention_weights = np.exp(attention_scores) / np.sum(np.exp(attention_scores))
    
    # Compute weighted sum of values
    attention_output = np.dot(attention_weights, value)
    
    print("Query Vector:\n", query)
    print("Key Matrix:\n", key)
    print("Value Matrix:\n", value)
    print("Attention Scores:\n", attention_scores)
    print("Attention Weights (Softmax):\n", attention_weights)
    print("Attention Output:\n", attention_output)

if __name__ == "__main__":
    calculate_attention()


Query Vector:
 [[0.37454012 0.95071431 0.73199394 0.59865848]]
Key Matrix:
 [[0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]
Value Matrix:
 [[0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]]
Attention Scores:
 [[0.76780201 1.4940289  0.75654844 1.10337231]]
Attention Weights (Softmax):
 [[0.18332433 0.37898014 0.18127284 0.25642268]]
Attention Output:
 [[0.40907837 0.57487469 0.48697096 0.50025049]]
